name: ci

on:
  push:
    branches: [ main, development, test ]
  pull_request:
    branches: [ main, development, test ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    environment:
      name: "${{ github.ref_name == 'main' && 'production' || github.ref_name == 'development' && 'development' || github.ref_name == 'test' && 'test' || 'development' }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: vars
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          ENV="${{ secrets.NODE_ENV }}"
          echo "image=ghcr.io/${OWNER}/${REPO}-${ENV}" >> "$GITHUB_OUTPUT"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.image }}
          tags: |
            type=raw,value=${{ github.run_number }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show image reference
        run: |
          echo "Pushed:"
          echo "${{ steps.meta.outputs.tags }}"